### ISSUE TITLE
Errata: Video mentions that the SourceTree GUI client for Git is available for Linux; unfortunately, this statement is incorrect

### ISSUE THREAD

**Issue by tonedef71** [ParkinT/mastering_git#3]
<b>Errata:</b> Approximately halfway through the Section 7.3 video, "GUI Clients for Git", it is mentioned that "SourceTree is another very simple and elegant tool and is available for Windows, Mac, <i>and Linux.</i>"  Currently (and for the foreseeable future) the SourceTree GUI client for Git is only available for the Mac OS X and Microsoft Windows operating systems:

![sourcetreeapp](https://cloud.githubusercontent.com/assets/3978924/6586163/c8de2e8e-c74d-11e4-9b99-f6b504305c1b.png)

**Comment by ParkinT** [comment]
Apologies for my misstatement while recording the audio narration.
Thanks for pointing this out and providing the errata.

> I hope, overlooking this small mistake, you found the video series valuable and worthy of recommendation to others

**Comment by tonedef71** [comment]
<blockquote >I hope, overlooking this small mistake, you found the video series valuable and worthy of recommendation to others</blockquote >
Yes, I enjoyed the video series and would recommend it to my colleagues.
